import sys,importlib,json
sys.path.insert(0,'docs/0930/sources');b=importlib.import_module('a-browser-capture')
for lang,name in [('zh-Hans-CN','06-devday-chinese.png'),('en-US','07-devday-english.png')]:
 b.call('open',f'https://openai.com/{lang}/index/devday-2026-recap/')
 b.call('eval','[...document.querySelectorAll("button")].find(e=>e.innerText==="GPT-6.1 Sol"&&e.getBoundingClientRect().height>0)?.click();true')
 b.call('eval','new Promise(r=>setTimeout(r,800))')
 b.call('eval','[...document.querySelectorAll("button")].find(e=>e.innerText==="GPT-6.1 Sol"&&e.getBoundingClientRect().height>0)?.scrollIntoView({behavior:"instant",block:"center"});true')
 b.call('eval','new Promise(r=>setTimeout(r,800))')
 print(b.call('eval','JSON.stringify({y:scrollY,button:[...document.querySelectorAll("button")].filter(e=>e.innerText==="GPT-6.1 Sol").map(e=>({top:e.getBoundingClientRect().top,expanded:e.getAttribute("aria-expanded")}))})'),flush=True)
 b.call('screenshot',str((b.I/name).resolve()))
 b.log(dict(id=name,url=f'https://openai.com/{lang}/index/devday-2026-recap/',time_bjt=b.stamp(),tool='opencli browser screenshot native viewport after expanding Sol accordion',status='success',file='images/'+name))
b.call('open','https://www.anthropic.com/research/glm-5-3-and-the-spread-of-advanced-cyber-capabilities')
b.call('eval','document.querySelectorAll("figure")[4].scrollIntoView({behavior:"instant",block:"start"});true')
b.call('eval','new Promise(r=>setTimeout(r,2000))')
f=b.call('eval','JSON.stringify({y:document.querySelectorAll("figure")[4].getBoundingClientRect().top+scrollY,h:document.querySelectorAll("figure")[4].getBoundingClientRect().height})')
b.shot('12-engagement-full.png',f['y']-90,int(f['h']+230))
b.call('open','https://www.whitehouse.gov/presidential-actions/2026/09/inaugurating-the-era-of-super-intelligence/')
b.call('eval','[...document.querySelectorAll("button")].find(e=>e.innerText.trim()==="MENU")?.click();true')
print(b.call('eval','JSON.stringify([...document.querySelectorAll("button,a")].filter(e=>e.innerText.trim()==="PRIORITIES"||e.innerText.trim()==="Priorities").map(e=>({tag:e.tagName,html:e.outerHTML.slice(0,700)})))'),flush=True)
