import json,pathlib,datetime
p=pathlib.Path('docs/2610/1002/sources')
def body(n):return json.loads((p/(n+'-browser.json')).read_text(encoding='utf8'))['text']
def para(n,needle):return next(x for x in body(n).split('\n\n') if needle in x)
def clean(s):return s.replace('|','\\|').replace('\n','<br>')
a='https://blog.google/innovation-and-ai/models-and-research/google-research/'
u1=a+'project-suncatcher-prototype/';u2=a+'google-project-suncatcher-facts/';j='https://www.cell.com/joule/fulltext/S2542-4351(26)00362-4';n='https://www.npr.org/2026/10/01/nx-s1-5983697/project-suncatcher-google-ai-data-center-space'
rows=[]
def row(*x):rows.append('| '+' | '.join(clean(str(t)) for t in x)+' |')
row('A1 原型星入轨、联系、后续数周测试','L1',u1,para('a-prototype','Today, our prototype')+' / '+para('a-prototype','This is the first step'),'01-suncatcher-prototype.png','Travis Beals, Senior Director, Paradigms of Intelligence；页面Oct 01,2026；JSON-LD datePublished 2026-10-01T23:30:00+00:00=北京10-02 07:30；正文未给TPU数量/Gemma/Gemini/15分钟','已找到')
row('A2 地面辐射与热真空舱','L1',u2,para('a-facts','Once the TPU chips')+' / '+para('a-facts','We’re working on'),'02-suncatcher-hardware.png；03-suncatcher-cooling.png','2026-09-24；UC Davis地面质子束，非在轨五年验证；后续在轨散热待测试','已找到')
row('A3 最多8倍太阳能、未来每星数十TPU、2027两星激光','L1',u2,para('a-facts','In low Earth orbit')+' / '+para('a-facts','Future designs')+' / '+para('a-facts','The technology in space'),'04-suncatcher-scale.png；05-suncatcher-power.png','up to；Future designs；2027是计划；不是此次原型星配置','已找到')
row('A4 Joule标题、作者、摘要和数字','L1',j,'Toward a future space-based, highly scalable AI infrastructure system design / '+next(x for x in body('a-joule').split('\n') if x.startswith('The sun is the largest energy source')),'07-suncatcher-joule.png','2026-10-01，官方未给时刻；DOI 10.1016/j.joule.2026.102678；HTML全文已存，PDF被403故页码未取得，关键摘句按节定位见a-joule-key-excerpts.md','部分支持')
row('A5 2025首发计划','L1','https://blog.google/innovation-and-ai/technology/research/google-project-suncatcher/','Our next step is a learning mission in partnership with Planet to launch two prototype satellites by early 2027 that will test our hardware in orbit, laying the groundwork for a future era of massively-scaled computation in space.','无','HTML文本节点拆分，句子从连续节点拼接；JSON-LD 2025-11-04T17:00:00Z=北京11-05 01:00；首发短博文本身无81/650/$200数字；研究长文另存a-research.html/txt','已找到')
row('A6 NPR四颗TPU、冰箱大小、Gemma、15分钟','L4',n,para('a-npr','Google just put a refrigerator-sized')+' / '+para('a-npr','The prototype satellite has four'),'06-suncatcher-npr.png','John Ruwitch、Geoff Brumfiel；10-01 14:41 ET=北京10-02 02:41；该数字段为记者叙述，未逐项署名发言人/论文；不是Google一手证明；后文Beals说Google will then fire up and test TPUs','未找到一手来源')
row('A7 Planet与SpaceX发射和载荷','L1/L3','https://www.spacex.com/launches/transporter18/ ; https://investors.planet.com/news/news-details/2026/Planet-Launches-Suncatcher-Tanager-2-and-18-SuperDove-Satellites/default.aspx',para('a-spacex','On Thursday, October 1')+' / '+para('a-planet-new','Developed in partnership with Google'),'无','SpaceX实发10-01 11:32 PT(PDT UTC-7)=18:32 UTC=北京10-02 02:32；130总载荷；M1 T+01:01:25（近似）。Planet自家20星含M1、Tanager-2、18 SuperDoves；无4TPU/冰箱大小规格','部分支持')
row('A8 Google官方X帖时间与互动','L1','https://x.com/search?q=Suncatcher%20from%3AGoogleResearch','未取到有效帖正文','无','两次OpenCLI查询超时；见d-a-x-error.txt。未提取账号凭据或登录信息','未找到一手来源')
row('A9 热度','L5/L6','https://aihot.news ; https://news.ycombinator.com/item?id=49928461 ; https://news.ycombinator.com/item?id=49932191','AI 评分 80；另有 3 家信源报道','无','北京2026-10-02 21:23 HN API：5分0评、4分1评；9/24旧帖49830606为233分547评，不能作为本次入轨帖热度。AIHOT21:26存档。Reddit见d-a-reddit-post-browser.json，搜索接口Failed to fetch；媒体采样NPR、Cocoloop（中英同一家），不是独立报道总量','部分支持')
row('A10 中英文Gemini已运行的实际转述','L5','https://news.cocoloop.cn/2026/10/google-suncatcher-tpu-in-orbit/ ; https://news.cocoloop.cn/en/2026/10/google-suncatcher-tpu-in-orbit/','每次跑大约 15 分钟 Gemini 推理就停机，等辐射器把热量散掉。 / Each burst lasts around 15 minutes of Gemini inference, then the chips power down while the radiator sheds the heat.','无','中页2026-10-02，英页2026-10（未给时刻）；发布方Cocoloop Editorial。中文与英文是同站。相对Google原文只确认联系和预期运作、后续数周收数据，转述的在轨推理/Gemini无对应一手支持；NPR为Gemma且will run。未找到明确写辐射在轨五年通过的实际文章','部分支持')
head='# A组事实清单（1002）\n\n抓取时间见 a-capture-log.jsonl，均为北京时间。页面快照与原始HTTP响应分开：Joule/Planet的HTTP403不是正文，*-browser.json才是成功的原站全文。7张截图均原站OpenCLI CDP 2倍设备像素比，CSS宽1100，无重绘；已人工视觉复核。\n\n| 说法 | 级 | 一手来源 URL | 原文摘句（原语言，逐字） | 截图文件 | 条件/口径/时区 | 状态 |\n|---|---|---|---|---|---|---|\n'
(p/'a-evidence.md').write_text(head+'\n'.join(rows)+'''\n\n## 可能的吠点\n\n- 已入轨并取得联系不等于已完成AI推理或在轨辐射资格验证；Google使用未来时说明“Over the coming weeks”。\n- 四颗TPU、冰箱大小、Gemma每次15分钟在NPR有文字，但该段未交代逐项消息来源，尚不能升级为Google原始发布。NPR采访另有Beals原话，并不自动使整篇数字都变L2。\n- Joule 81星/650km是“illustrative”编队模型，不是此次卫星实测轨道，更非已部署规模。\n- $200/kg是带假设的发射价格情景和摊销供电成本比较；原文明确不是全面经济可行性研究。论文采用现价$3,600/kg(Falcon9 reusable)，不是线索中的$2,700/kg；两者未自行调和。\n- “SpaceX Starmind 2027 Q4”未找到一手支持；NPR反而写as early as 2028，二手不能拿来确定时间线。\n- HN大讨论主要来自9/24预告，不能把旧帖233分547评论套在10/2入轨新帖上。\n\n## 社区质疑线索（L6）\n\nHN https://news.ycombinator.com/item?id=49834478 （lastscattering）指出81星紧密编队的间距和控制难度；原句见 d-a-hn-comment-candidates.json。Algolia返回该评论points=null，HN公开页通常不显示评论分数，因此不标“高赞”。Joule的Orbital dynamics节支持这是一种示例编队并仍有工程折衷。\n\n## 已知缺口\n\nJoule PDF页码、官方X有效帖及互动、NPR数字的独立一手出处仍缺。截图07的Summary标题被网站粘性栏部分遮挡，但摘要正文完整；不作为排版成品。没有凭未找到推断事实为假。\n''',encoding='utf8')
text=body('a-joule');needles=['illustrative, planar','current launch price $3,600','not intended as a comprehensive','Effective thermal management','A published ballpark','Testing was conducted at the UC Davis','at least 64','hundreds of TPUs','full life cycle assessment']
lines=['# Joule关键摘句（HTML节定位，PDF页码未取得）','','URL: '+j,'DOI: 10.1016/j.joule.2026.102678','','作者：'+', '.join(json.loads((p/'a-joule-metadata.json').read_text())['authors']),'']
for needle in needles:
 for i,line in enumerate(text.splitlines(),1):
  if needle in line:lines+=['## HTML纯文本第'+str(i)+'行（关键词 '+needle+'）',line,'']
(p/'a-joule-key-excerpts.md').write_text('\n'.join(lines),encoding='utf8')
