# Checks that quoted strings used in evidence-d.md occur verbatim (whitespace-normalised) in the named archive file.
# usage: python3 d-verify-quotes.py   (run from docs/2610/1007/sources/)
import re, html

def load(f):
    t = open(f, encoding='utf8', errors='replace').read()
    t = html.unescape(t)
    t = t.replace('ﬃ', 'ffi').replace('ﬀ', 'ff').replace('ﬁ', 'fi').replace('ﬂ', 'fl')
    if f.endswith('.html'):
        t = re.sub(r'<script[\s\S]*?</script>|<style[\s\S]*?</style>', ' ', t)
        t = re.sub(r'<[^>]+>', ' ', t)
    return re.sub(r'\s+', ' ', t)

checks = [
('d-playground-blog.txt', "Playground launches today for users in the U.S. (18+) at playground.google, with tiered creation access rolling out based on your Google AI subscription."),
('d-playground-blog.txt', "Unity Spark is currently in testing, with closed beta coming soon."),
('d-playground-blog.txt', "Today, we’re introducing Playground, an experimental gaming platform that lets you create, play, and share custom games."),
('d-playground-blog.txt', "every published game undergoes safety screenings aligned with our Community Guidelines, along with user reporting."),
('d-playground-blog.txt', "Playground games support in-game leaderboards and multiplayer gameplay in select genres."),
('d-playground-blog.txt', "Playground is home to an ever-growing catalog of community games."),
('d-playground-verge.txt', "Playground will be available today in the US for users who are 18 and older at playground.google."),
('d-playground-verge.txt', "Playground is free to use, but if you have a Google One subscription, you’ll have higher weekly token limits based on your plan, Google spokesperson Nia Carter tells The Verge."),
('d-playground-verge.txt', "Under the hood, Playground is powered by “Google’s existing foundation models (Gemini, Nano Banana, and Lyria) paired with a custom harness refined through our own internally built games and evaluations,” Carter says."),
('d-playground-verge.txt', "A closed beta for Spark is scheduled to kick off later this year, and people who are interested can get on a waitlist starting today."),
('d-playground-decoder.txt', "The closed beta is set to launch sometime in 2026."),
('d-playground-unity-news.txt', "later this year Google and Unity will introduce an expanded creation experience called Unity Spark"),
('d-playground-unity-news.txt', "Creators can test out Playground at playground.google.com"),
('d-playground-unity-news.txt', "Users can log in with their Google Play Games profile to easily access built-in leaderboards, multiplayer matchmaking, and community features"),
('d-playground-straitstimes.txt', "The market reaction on Oct 7 was more muted. Unity shares were little changed while shares in Roblox, a gaming platform where people create their own games, were down less than 1%."),
('d-playground-investing-firecrawl-excerpt.txt', "Roblox Corp shares fell as much as 8% in pre-market trading Wednesday and were recently down about 5%"),
('d-synthid-blog.txt', "Since launching Google SynthID in 2023, we've helped people identify AI-generated media using imperceptible watermarks across images, video, and audio. To date, we've watermarked over 180 billion images and videos, along with 240,000 years of audio content."),
('d-synthid-blog.txt', "With the new SynthID Detector, anyone can easily check if an image, video, or audio file was made with AI from Google or our partners, including OpenAI, NVIDIA, Kakao, and soon, Apple."),
('d-synthid-blog.txt', "This tool joins our built-in verification features in Search, the Gemini app, and Chrome, which now regularly handle over 1 million requests daily."),
('d-synthid-blog.txt', "Now, we’re expanding access to everyone – with the tool available globally in English starting today."),
('d-synthid-site-rendered.txt', "This is not a general AI detector. We can only detect media from the above companies, who have adopted SynthID technology. We are continuously working on extending our partnerships to allow detecting more generated media."),
('d-synthid-site-rendered.txt', "This technology was pioneered by Google DeepMind and has been adopted by Nvidia, OpenAI, and Kakao."),
('d-synthid-site-rendered.html', "SynthID is an approach for watermarking and identifying AI-generated content generated by models across Google, Nvidia, OpenAI, and Kakao."),
('d-synthid-site-rendered.html', "In very rare cases SynthID can also falsely trigger on non-watermarked content."),
('d-synthid-site-rendered.html', "However, no signal is completely robust and we recommend collecting multiple points of data before making a decision."),
('d-synthid-site-rendered.html', "Third-Party Sign-In Profiles: If you authenticate using a third-party account (such as Apple), Google processes and retains basic account identifiers shared by your provider"),
('d-synthid-site-rendered.html', "To enforce daily usage quotas and defend the service against automated attacks, we securely store a digital signature of your media."),
('d-synthid-site-rendered.html', "Create multiple accounts, leverage automated tools, or manipulate system identifiers to circumvent the service's rate-limiting restrictions."),
('d-synthid-site-rendered.html', "The SynthID Detector currently supports three content types"),
('d-synthid-site-rendered.html', "Watermark not detected: No confident signal was found, so it was not likely to have been edited or generated by a SynthID-enabled AI model. Although this does not totally rule out AI generation or manipulation."),
('d-synthid-old1.txt', "Over 10 billion pieces of content have already been watermarked with SynthID."),
('d-synthid-old1.txt', "We are starting to roll this out to early testers today, before making it available more broadly. Journalists, media professionals and researchers can join our waitlist to gain access to the SynthID Detector."),
('d-synthid-old2.txt', "watermarking over 100 billion images and videos and 60,000 years of audio."),
('d-synthid-old2.txt', "Already, it’s been used 50 million times globally"),
('d-nemotron-blog.txt', "It was an unofficial, unsupervised benchmark and was not included in the official IOI ranking. The IMO system’s submitted proofs were graded by official IMO graders."),
('d-nemotron-blog.txt', "For competitive programming, the Nemotron-3-Ultra-CC model is available on Hugging Face"),
('d-arxiv-2609.02849.txt', "We use DeepSeek-V4-Flash to generate 1.2 million reasoning traces for Nemotron-3-Nano-30B-A3B and 477,642 traces for NVIDIA-Nemotron-3-Ultra-550B-A55B"),
('d-arxiv-2609.02849.txt', "We therefore select GLM-5.2 training data for the live run."),
('d-arxiv-2609.02849.txt', "GLM-5.2 achieves a higher score with shorter outputs than DeepSeek-V4-Flash, as shown in Table 2."),
('d-arxiv-2609.02849.txt', "During the live inference deployment, we used a peak allocation of up to 760 NVIDIA GB300 GPUs."),
('d-arxiv-2609.02849.txt', "We plan to release our competition Nemotron-3-Ultra-CC checkpoint together with runnable inference and evaluation recipes in NeMo-Skills."),
('d-arxiv-2609.02849.txt', "The live IOI result should therefore be interpreted as a system-level comparison under the same time and submission limits, rather than an equal-resource comparison with human contestants."),
('d-arxiv-2609.02849.txt', "Our system was not an official IOI contestant and the run was not supervised by IOI. Therefore, its score was not included in the official rankings and the evaluation is reported as an unofficial, unsupervised benchmark."),
('d-arxiv-2609.02849-abs.txt', "To our knowledge, this is the first AI system to outscore the highest-scoring human contestant on an IOI problem set."),
('d-arxiv-2609.10712.txt', "Official result. The system participated officially in IMO 2026 and scored 30 out of 42 points, above the gold-medal cutoff of 29; all submitted proofs were graded by official IMO graders."),
('d-arxiv-2609.10712.txt', "We release Nemotron-3-Ultra-SFT as nvidia/Nemotron-3-Labs-Ultra-Math-SFT and Nemotron-3-Ultra-RL as nvidia/Nemotron-3-Labs-Ultra-Math-RL, both under the OpenMDW-1.1 license of the base model."),
('d-arxiv-2609.10712-abs.txt', "We release the two post-trained checkpoints as well as the training data, the training and inference code, the submitted solutions, and Nemotron-IMO-Bench, a new benchmark of 200 novel olympiad-level problems."),
('d-nemotron-hf-model-readme.md', "fine-tuned for one epoch on 477,642 synthetic reasoning traces distilled from GLM-5.2 across 22,000 curated problems"),
('d-nemotron-hf-model-readme.md', "Post-training quantized to NVFP4 using the NVIDIA Model Optimizer NVFP4 recipe"),
('d-opentpu-readme.md', "**An open-source AI accelerator, developed by AI.**"),
('d-opentpu-readme.md', "It asks two questions: how far can AI agents go at hardware design, and can they build the chip that runs their own inference?"),
('d-opentpu-readme.md', "The design runs ten modern models with their real weights on an Inspur YPCB-00338 card (Xilinx Kintex-7 xc7k480t, two DDR3 channels), and the card produces the same tokens as the simulator, bit for bit."),
('d-opentpu-readme.md', "Every configuration matches the simulator token for token, per-position and with the resident decode program."),
('d-opentpu-readme.md', "It matches Hugging Face's greedy tokens on three prompts with either head."),
('d-opentpu-readme.md', "It is measured on Qwen3-0.6B, LFM2.5-230M, Qwen3.5-0.8B and Gemma 4 E2B; the MoE models are not supported."),
('d-opentpu-readme.md', "Measured on the card: the first three models on 2026-09-29 with the production image `deploy_champ_e698dcd7`. LFM2-2.6B, SmolLM3-3B and Phi-4-mini on 2026-09-30, and Qwen3.5-2B and 4B and Gemma 4 on 2026-10-01, with build B, `deploy_fused133c_79c5707a`, production since then."),
('d-opentpu-readme.md', "decode is 64 greedy tokens after a 512-token prompt, with the host's argmax in the loop (not streamed)."),
('d-opentpu-readme.md', "| LFM2.5-230M | int8 | 59.0 tok/s | 52.3 tok/s |"),
('d-opentpu-readme.md', "| Qwen3-0.6B | int8 | 21.6 tok/s | 21.3 tok/s |"),
('d-opentpu-readme.md', "3.95 tok/s, with Hugging Face's 16 greedy tokens. 62% of expert uses hit, and 153 MB streamed per token at 1.41 GB/s over PCIe"),
('d-opentpu-readme.md', "(build 84989047, 2026-10-07: `--no-golden --save` under the lock, `--against` on a build host), all six runs of Qwen3-0.6B, LFM2.5-230M and Qwen3.5-0.8B, in int8 and in 4-bit with an int8 head, gave the ISA simulator's tokens and bit-identical logits on every prompt"),
('d-opentpu-docs-tourney-md.txt', "`tools/tourney/` evolves one RTL component at a time with LLM agents"),
('d-opentpu-docs-tourney-md.txt', "merging a champion into `main` is a human decision (`git merge tourney/<comp>`)."),
('d-opentpu-docs-status-md.txt', "**Component tournaments** (`tools/tourney`, Opus agents, yosys evaluation):"),
('d-opentpu-hn-item.json', "After using AI to develop risc-v CPU cores, the same technique was used for developing openTPU."),
('d-opentpu-hn-item.json', "trough a recursive self improvement loop got to 80+ tok/sec on the smallers models."),
('d-metr-blog.txt', "We have not observed agents exploiting this in any of our evaluations; this is just a proof-of-concept exploit."),
('d-metr-blog.txt', "This vulnerability was relatively narrow: it just affects what is shown through the viewer, and the underlying transcripts aren’t modified."),
('d-metr-blog.txt', "Meridian Labs, the team behind Inspect, patched the vulnerability within one day of reporting. Coincidentally, on October 1st they merged this PR which introduces an “untrusted mode” which disables rendering of agent outputs."),
('d-metr-blog.txt', "We haven’t searched our evaluations for this specific exploit, but we have searched more generally for misalignment or security incidents, and we expect that attempting to exploit this vulnerability would have been flagged by this broader search. We plan to share more information about this review of our evaluation logs in the upcoming weeks."),
('d-metr-blog.txt', "With help from an AI agent, a researcher found a vulnerability in about 10 minutes that could have allowed an agent to arbitrarily modify what the reviewer sees."),
('d-metr-blog.txt', "Given how evaluations are run within METR’s infrastructure, the real trajectory would still exist in our database, so the agents’ misbehavior could be discovered eventually, but the human reviewer would need to know to look for this"),
('d-metr-blog.txt', "Note that the underlying data in the transcript doesn't change, and still would have been available in a database."),
('d-metr-blog.txt', "To reduce the risk of this investigation itself causing a security incident, this red-teaming work was conducted on a special staging sandbox deployment that is isolated from METR’s production infrastructure."),
('d-metr-inspect-issue-4318-comments.json', "This is now fixed on main for both Inspect and Scout:"),
('d-cursor-changelog.txt', "Remote Control is on by default for everyone except Enterprise organizations."),
('d-cursor-changelog.txt', "Remote control doesn't move your agents anywhere. It keeps running on your computer, and the app connects to it. Your computer needs to stay on and online for remote control to work."),
('d-cursor-changelog.txt', "To stop your computer from sleeping while you're away, turn on \"Keep this computer awake\" under Remote Control in Cursor's desktop settings. Your computer needs to be plugged in with the lid open."),
('d-cursor-changelog.txt', "Remote control is on by default, except for Enterprise organizations. Enterprise admins can turn it on in Org settings > Security and identity > Remote control."),
('d-cursor-changelog.txt', "Remote control is available today in the Cursor iOS app."),
('d-cursor-changelog.txt', "Remote control doesn't require cloud agents to work."),
]

bad = 0
for f, q in checks:
    t = load(f)
    qq = re.sub(r'\s+', ' ', q)
    if qq in t:
        continue
    # pdftotext hyphenation artefacts ("OpenMDW- 1.1") and JSON unicode escapes
    t2 = t.replace('- ', '-')
    q2 = qq.replace('- ', '-')
    if q2 in t2:
        continue
    bad += 1
    print('MISSING', f, '::', q[:120])
print('checked', len(checks), 'missing', bad)
