from pathlib import Path
import re,json,datetime,hashlib
from PIL import Image
P=Path('docs/0930/sources'); I=P.parent/'images'
f=P/'evidence.md';t=f.read_text(encoding='utf-8-sig')
t=t.replace('| , which measures how well AI models', '| First, we ran the model on<br>ExploitBench<br>, which measures how well AI models')
t=t.replace('<br><br>). Here, the researcher focused', '<br><br>In a second session, a researcher used GLM-5.3-Flash (a smaller, less capable version of GLM-5.3) to develop an exploit for a<br>known<br>vulnerability (we’ve previously written about these “N-day” vulnerability exploits<br>here<br>). Here, the researcher focused')
t=t.replace('At Zhipu’s API prices, this effort would have cost $20.40. |', 'At Zhipu’s API prices, this effort would have cost $20.40.<br><br>A redacted screenshot of an exploit page generated by GLM-5.3 during researcher-driven testing, shown stealing a user’s SSH private key via a malicious website. The exploit chains together multiple 0-day vulnerabilities the model discovered in a component of a popular web browser, reading a sensitive file off the user’s computer. |')
t=t.replace('which enabled trusted cyber defenders to find |', 'which enabled trusted cyber defenders to find<br>more than 10,000 vulnerabilities<br>in critical software, giving them a head start before malicious actors had access to similarly capable models. |')
t=t.replace('L1；NIST对第三方发布事实为L3', 'L1（开发者）；NIST所述发布日期另行归因')
t=t.replace('官方文档与限定官方域搜索未找到', '官方文档、限定官方域及 site:x.com/Zai_org 搜索未找到')
t=t.replace('Intelligence.’” (<br>', 'Intelligence.’”<br>')
t=t.replace('<br><br>SEE IT IN ACTION<br><br>How we\'re advancing<br><br>AI<br><br><br>Executive Orders<br><br>Fact Sheets<br><br>Rem |', ' |')
# Historical row: retain standard-price excerpt; long-context prices are separately documented in A2.
lines=t.splitlines()
for i,line in enumerate(lines):
 if line.startswith('| A3 '):
  cells=line.split(' | ')
  cells[3]='gpt-6-sol<br>$2.00<br>$0.20<br>$2.50<br>$10.00<br><br>2026-09-22T18:12:13.000Z'
  cells[5]+=' 引句价格列依次为input/cached input/cache writes/output；省略制表空白，完整历史行见a-history-price-excerpts.json。'
  lines[i]=' | '.join(cells)
t='\n'.join(lines)+'\n';f.write_text(t,encoding='utf-8')
# Lossless semantic image processing: proportional downscale only; no page-text changes.
resized=[]
for p in I.glob('*.png'):
 with Image.open(p) as im:
  if im.width>1400:
   old=im.size;im.resize((1400,round(im.height*1400/im.width)),Image.Resampling.LANCZOS).save(p);resized.append([p.name,old])
(P/'a-image-normalization.json').write_text(json.dumps({'time_bjt':datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).isoformat(),'operation':'proportional downscale to width 1400; no redrawing or text edits','files':resized},ensure_ascii=False,indent=2),encoding='utf-8')
print('evidence quote boundaries corrected; resized',len(resized))
